
'use server';

import type { CartItem } from '@/app/layout';
import { revalidatePath } from 'next/cache';
import { createClient } from '@supabase/supabase-js';

// Define the Order type for database interaction
export interface Order {
  id: string; // The order ID, generated by the database
  created_at: string; // The date, generated by the database
  user_id: string; // The user's ID
  customer_name: string;
  customer_email: string;
  items: CartItem[]; // Stored as JSONB
  total: number;
  status: 'قيد المعالجة' | 'مكتمل' | 'مرفوض' | 'ملغي';
  shipping_address: string;
  proof_of_purchase_url?: string;
}


// Server Action to create an order
export async function createOrder(
  orderData: {
    userId: string;
    customerName: string;
    customerEmail: string;
    shippingAddress: string;
    total: string;
    items: string;
    proofOfPurchaseUrl: string | null;
  }
): Promise<{ order?: Order; error?: string }> {
  
   const {
      userId,
      customerName,
      customerEmail,
      shippingAddress,
      total,
      items,
      proofOfPurchaseUrl
  } = orderData;

  if (!userId) {
     return { error: 'المستخدم غير مصادق عليه. يرجى تسجيل الدخول مرة أخرى.' };
  }

  // Use the Service Role Key for robust server-side actions
  const supabaseAdmin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

  try {
    const orderToInsert = {
      user_id: userId,
      customer_name: customerName,
      customer_email: customerEmail,
      shipping_address: shippingAddress,
      total: parseFloat(total),
      items: JSON.parse(items),
      status: 'قيد المعالجة' as const,
      proof_of_purchase_url: proofOfPurchaseUrl,
    };

    const { data: newOrder, error: insertError } = await supabaseAdmin
        .from('orders')
        .insert(orderToInsert)
        .select()
        .single();
    
    if (insertError) {
        console.error('DB Insert Error:', insertError);
        return { error: `فشل إنشاء الطلب في قاعدة البيانات: ${insertError.message}` };
    }
    
    // After creating the order, create notifications for all admin users
    const { data: admins, error: adminError } = await supabaseAdmin
        .from('users')
        .select('id')
        .eq('role', 'admin');

    if (adminError) {
        console.error('Error fetching admins for notification:', adminError);
        // Don't fail the whole transaction, just log the error
    } else if (admins) {
        const notifications = admins.map(admin => ({
            user_id: admin.id,
            title: 'طلب جديد مستلم',
            message: `تم استلام طلب جديد من ${customerName}.`,
            link: `/admin/orders`,
        }));

        const { error: notificationError } = await supabaseAdmin
            .from('notifications')
            .insert(notifications);

        if (notificationError) {
            console.error('Error creating notifications:', notificationError);
        }
    }


    revalidatePath('/profile'); // Revalidate the profile page to show the new order
    revalidatePath('/admin/orders'); // Revalidate admin orders page
    return { order: newOrder as Order };

  } catch (e: any) {
      console.error('Unexpected error in createOrder:', e);
      return { error: e.message || 'حدث خطأ غير متوقع.' };
  }
}

// Server Action to get orders for the current user
export async function getMyOrders(userId: string): Promise<{ orders?: Order[]; error?: string }> {
    if (!userId) {
        return { error: 'معرف المستخدم مطلوب' };
    }
    try {
        const supabaseAdmin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
        const { data, error } = await supabaseAdmin
            .from('orders')
            .select('*')
            .eq('user_id', userId)
            .order('created_at', { ascending: false });

        if (error) {
            console.error('Error fetching orders:', error);
            return { error: error.message };
        }

        return { orders: data as Order[] };

    } catch (e: any) {
        return { error: e.message };
    }
}


export async function getCurrencySettings(): Promise<{ symbol: string, imageUrl: string | null }> {
    try {
        const supabaseAdmin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
        const { data, error } = await supabaseAdmin.from('settings').select('key, value').in('key', ['currency_symbol', 'currency_symbol_image_url']);

        if (error) throw error;

        const settingsMap = new Map(data.map(s => [s.key, s.value]));
        
        return {
            symbol: settingsMap.get('currency_symbol') || 'ر.س',
            imageUrl: settingsMap.get('currency_symbol_image_url') || null,
        };

    } catch(e: any) {
        console.error('Failed to fetch currency settings:', e);
        return { symbol: 'ر.س', imageUrl: null };
    }
}
